#!/bin/bash

#downloading attendance file
#wget -O attendance https://inductions.delta.nitt.edu/sysad-task1-attendance.log

#getting date
match=$(date "+%Y-%m-%d")
#echo $match

#getting list of soldiers present

cat /root/attendance | grep "Army" | grep "^+$match" | grep -w "YES" | cut -d " " -f2,3  > /home/ArmyGeneral/attendance_record
cat /root/attendance | grep "Navy" | grep "^+$match" | grep -w "YES" | cut -d " " -f2,3 > /home/NavyMarshal/attendance_record
cat /root/attendance | grep "AirForce" | grep "^+$match" | grep -w "YES" | cut -d " " -f2,3 > /home/AirForceChief/attendance_record


echo Done
