#!/bin/bash

#creating users
useradd ChiefCommander -m -s /bin/bash 
useradd ArmyGeneral -m -s /bin/bash 
useradd NavyMarshal -m -s /bin/bash 
useradd AirForceChief -m -s /bin/bash 

for  i in {1..50}
do
        useradd Army$i -m -s /bin/bash
        useradd Navy$i -m -s /bin/bash
        useradd AirForce$i -m -s /bin/bash
done

echo Users Created successfully
