#!/bin/bash

#creating users
sudo userdel -r CheifCommander 
sudo userdel -r ArmyGeneral  
sudo userdel -r NavyMarshal  
sudo userdel -r AirForceCheif  

for  i in {1..50}
do
        sudo userdel -r Army$i
        sudo userdel -r Navy$i 
        sudo userdel -r AirForce$i 
done

echo Users Created successfully
