#!/bin/bash

#creating file
#sudo touch /home/CheifCommander/nearest10

#getting position of present soldiers
diff -y /root/attendance /root/position | grep YES > prac3


#getting the date, name and  N and E cordinates in a single file
c=$(awk '{print $1, $2,$7,$8}' prac3 | sed 's/N°//' | sed 's/E°//') 
echo -e "$c\n" > prac4
echo DONE -1
echo


#using the distance formula and getting top 10 nearest
awk '{print $1,$2,((($3 - 28.7041) ^ 2) + (($4 - 77.1025) ^ 2)) }' prac4 |sort -k3 -n | head > /home/ChiefCommander/nearest10
echo Done-2



